### ISSUE TITLE
Some ideas for BLD

### ISSUE THREAD

**Issue by hrstoyanov** [rife2/bld#38]
@gbevin @ethauvin 

Here are some ideas after I tried to oragniza 3 re-usable java libraries and an app that uses them with BLD. I think I got what I wanted, but the experience was not straightforward and I did not feel productive, maybe also because I think I was pushing BLD to do thing no one had tried. 

There are 2 problems worth mentioning:
- mult-module setup would require BLD code that is pretty much boilerplate that no one need to write manually for the most part.
- generating  multi-module IntelliJ/VSCode is just as important and could be a an even bigger time waster.

To help with that, I propose the initial code generating wizard to be expanded beyond what it currently does: 1 bld + java source root (lib, app or base). However, if the wizard starts asking too much questions for multi-module setup, it could also become a bottleneck, as developers may need to re-generate their initial setup many times over, until they get it right. Therefore, a better approach is to make the wizard read a very tight and concise spec file, from which to generate all the boilerplate BLD java code + IDE configuration files. Here is what such specs file might  look like (using YAML, for example):

```yaml
# Platform definition
inventory:
   repository:
       - maven_central:
             libraries: 
                - liba: some.org:libA:1.2.3
                - libb: another.com:libB:1.3.4
        - rife2:
             ....     
project:
    modules:
      - module
          name: myapp
          type: app
          module_name: com.example.        # java modules should be optional?
          main_class: Main.  #Optional, default to Main
          package: com.example
      - module
         name: mylib1
         type: lib
         module_name: com.mylib
         package: com.mylib
      - module
        ....
dependencies:
    mylib:
       - compile: libb, mylib2
    myapp: 
        - compile: liba, mylib1
ide: intellij
```

The main idea is the boostrap wizard reads in specs file and generate all the boilerplate . The code quality of the boilerplate needs to be high quality, well annotated with comments and folowing "best BLD practices". It needs to scale to X libs, Y app and Z external modules. The generated codebase need to have just 1 **bld** folder and as many java module as specified, plus all IDE setup files.

**This idea can be extended even further** - build a website where the specs are requested with some sort of web forms, then the user gets to donload a ZIP (with the wrapper included!) file with all the boilerplate as if s/he ran the wizard command line. **This is what Spring and Quarkus do** on their web sites!

Once the code is generated, users can jump right into it. The BLD api is awesome already, so a capable Java developer can immediately start extending it. Alternatively, the user can re-generate the boilerplate **cheaply and repeatedly** as many time as needed, until s/he is satisfied.

**Now, the good news is that even now BLD has all the necessary functionality already baked in** - I know because I already wrote manually something like the above, and it works, and is possible. I only wish I did not have to re-invent the hot water and the wheel, but just get "recommended" boilerpalte code for my modules quickly, so  I can immediately load up in IntelliJ and see all my X modules.

BLD can still claim to be "imperative - doing only what you tell it to", but giving it this "declarative" compact specs file/web form boost only to get started with, will make it that much more competitive to Maven and Gradle!

      
   
      
        
        

```
